### ISSUE TITLE
Transition to Mono-Repo

### ISSUE THREAD

**Issue by lehni** [ditojs/dito#1]
@azertypow @koskimas @nicholaswmin @urshofer @bdaniel7 @puppycodes @jondashkyle @jongacnik @afincato @Awea @wearemd @bennyschudel @studioscholz @fpatrik:

Since you all stared some of the various Dito.js repos, I wanted to let you know of the transition to a mono-repo at https://github.com/ditojs/dito/

The other repos will be deleted shortly, and development will continue in one place using https://github.com/lerna/lerna

**Comment by studioscholz** [comment]
Thanks, stared again!


PS:
