### ISSUE TITLE
Drag functionality of list components in dito admin not working in firefox

### ISSUE THREAD

**Issue by pifragile** [ditojs/dito#14]
Firefox Version 64.0
Example:

![bildschirmfoto 2019-01-04 um 12 00 02](https://user-images.githubusercontent.com/14249275/50685295-e93f2580-1018-11e9-8fbe-729b1b1175b2.png)

**Comment by lehni** [comment]
@pifragile thanks for the report. Note that this project is public and shouldn't include too much private lineto info (not the case here, but just a heads up ;)

**Comment by pifragile** [comment]
aware of that :)

**Comment by lehni** [comment]
Crazy, this is still not working on Firefox. I thought it'd fix itself with time and updates :)

**Comment by lehni** [comment]
But their example does work on Firefox: https://sortablejs.github.io/Vue.Draggable/#/simple

**Comment by lehni** [comment]
Turns out it's a Firefox bug that happens when using <button> as the handle:

https://github.com/SortableJS/Sortable/issues/370

The bug is open since 11 years (!)
