### ISSUE TITLE
defaults in app configuration

### ISSUE THREAD

**Issue by puckey** [ditojs/dito#26]
- `env` could default to `process.env.NODE_ENV` when not supplied
- `server.host` could default to `env.NODE_HOST || env.HOST || '0.0.0.0'` when not supplied
- `server.port` could default to `env.NODE_PORT || env.PORT || 8080` when not supplied
- `log` and `server` could be made optional like app is

**Comment by lehni** [comment]
Good point! Would accept a PR ;)

**Comment by puckey** [comment]
See https://github.com/ditojs/dito/pull/34

I was wondering about logging defaults: how about having some turned on in development and disabling by default in production?

**Comment by lehni** [comment]
Good idea regarding logging defaults. Which ones do you suggest should be on in development by default?

**Comment by puckey** [comment]
We could use the defaults used in `dito-example`... In production everything is turned off and in development we have:

```
  log: {
    requests: false,
    routes: false,
    schema: false,
    relations: false,
    sql: false
  },
```

And how about the `app.cors.credentials` and `admin.api.cors.credentials` settings in `index.local.js` with the comment "Only required for Dito.js Admin development to work on different port:"? Might make sense to add these as a default also?
