### ISSUE TITLE
Fix logger typings

### ISSUE THREAD

**Issue by lehni** [ditojs/dito#98]
the logger is now set up like this:

```js
  setupLogger() {
    const { prettyPrint, ...options } = this.config.logger
    const transport = prettyPrint
      ? pino.transport({
          target: 'pino-pretty',
          options: prettyPrint
        })
      : null
    this.logger = pino(options, transport).child({ name: 'app' })
  }
```

We don't use `koa-pino-logger` or `koa-logger` anymore, jsut `pino` and `pino-pretty`, and `app.config.logger` gets split into `{ prettyPrint, ...options }`, of which `prettyPrint` are the `pino-pretty` options, and `…options` are the `pino` options.

This should be reflected in the server typings, but I don't know enough to figure out how to do this.

@puckey could you take care of it? Thank you!

**Comment by puckey** [comment]
Fixed in https://github.com/ditojs/dito/pull/100
